// Code generated by Deager. Do not edit.
package se.ansman.provider;

import dagger.Lazy;
import dagger.Module;
import dagger.Provides;
import dagger.hilt.InstallIn;
import dagger.hilt.codegen.OriginatingElement;
import dagger.hilt.components.SingletonComponent;
import dagger.multibindings.IntoSet;
import se.ansman.deager.Initializable;

@Module
@InstallIn(SingletonComponent.class)
@OriginatingElement(
    topLevelClass = ProviderModule.class
)
public abstract class EagerProviderModule {
  private EagerProviderModule() {
  }

  @Provides
  @IntoSet
  public static Initializable provideThingAsInitializable(Lazy<ProvidedThing> providedThing) {
    return Initializable.fromLazy(providedThing);
  }
}