// Code generated by Auto Dagger. Do not edit.
package se.ansman.internal_binding

import dagger.Lazy
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.codegen.OriginatingElement
import dagger.hilt.components.SingletonComponent
import dagger.multibindings.IntoSet
import se.ansman.dagger.auto.Initializable
import se.ansman.dagger.auto.Initializable.Companion.asInitializable

@Module
@InstallIn(SingletonComponent::class)
@OriginatingElement(topLevelClass = BindingModule::class)
internal object AutoInitializeBindingModule {
  @Provides
  @IntoSet
  public fun bindThingAsInitializable(thing: Lazy<Thing>): Initializable = thing.asInitializable()
}