// Code generated by Deager. Do not edit.
package se.ansman.nested

import dagger.Lazy
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.codegen.OriginatingElement
import dagger.hilt.components.SingletonComponent
import dagger.multibindings.IntoSet
import se.ansman.deager.Initializable
import se.ansman.deager.Initializable.Companion.asInitializable

@Module
@InstallIn(SingletonComponent::class)
@OriginatingElement(topLevelClass = Outer::class)
public object EagerOuterSomeThingModule {
  @Provides
  @IntoSet
  public fun provideSomeThingAsInitializable(someThing: Lazy<Outer.SomeThing>): Initializable =
      someThing.asInitializable()
}