// Code generated by Auto Dagger. Do not edit.
package se.ansman.priority

import dagger.Lazy
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.codegen.OriginatingElement
import dagger.hilt.components.SingletonComponent
import dagger.multibindings.IntoSet
import se.ansman.dagger.auto.Initializable
import se.ansman.dagger.auto.Initializable.Companion.asInitializable

@Module
@InstallIn(SingletonComponent::class)
@OriginatingElement(topLevelClass = Outer::class)
public object AutoInitializeOuterSomeThingModule {
  @Provides
  @IntoSet
  public fun provideSomeThingAsInitializable(someThing: Lazy<Outer.SomeThing>): Initializable =
      someThing.asInitializable(priority = 4711)
}