// Code generated by Deager. Do not edit.
package se.ansman.internal_object

import dagger.Lazy
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.codegen.OriginatingElement
import dagger.hilt.components.SingletonComponent
import dagger.multibindings.IntoSet
import se.ansman.deager.Initializable
import se.ansman.deager.Initializable.Companion.asInitializable

@Module
@InstallIn(SingletonComponent::class)
@OriginatingElement(topLevelClass = InternalObject::class)
internal object EagerInternalObjectModule {
  @Provides
  @IntoSet
  public fun provideInternalObjectAsInitializable(internalObject: Lazy<InternalObject>):
      Initializable = internalObject.asInitializable()
}