// Code generated by Deager. Do not edit.
package se.ansman.internal_object;

import dagger.Lazy;
import dagger.Module;
import dagger.Provides;
import dagger.hilt.InstallIn;
import dagger.hilt.codegen.OriginatingElement;
import dagger.hilt.components.SingletonComponent;
import dagger.multibindings.IntoSet;
import se.ansman.deager.Initializable;

@Module
@InstallIn(SingletonComponent.class)
@OriginatingElement(
    topLevelClass = InternalObject.class
)
public abstract class EagerInternalObjectModule {
  private EagerInternalObjectModule() {
  }

  @Provides
  @IntoSet
  public static Initializable provideInternalObjectAsInitializable(
      Lazy<InternalObject> internalObject) {
    return Initializable.fromLazy(internalObject);
  }
}