// Code generated by Deager. Do not edit.
package se.ansman.nested;

import dagger.Lazy;
import dagger.Module;
import dagger.Provides;
import dagger.hilt.InstallIn;
import dagger.hilt.codegen.OriginatingElement;
import dagger.hilt.components.SingletonComponent;
import dagger.multibindings.IntoSet;
import java.lang.String;
import se.ansman.deager.Initializable;

@Module
@InstallIn(SingletonComponent.class)
@OriginatingElement(
    topLevelClass = Outer.class
)
public abstract class EagerOuterInnerModule {
  private EagerOuterInnerModule() {
  }

  @Provides
  @IntoSet
  public static Initializable provideStringAsInitializable(Lazy<String> string) {
    return Initializable.fromLazy(string);
  }
}