// Code generated by Deager. Do not edit.
package se.ansman.initializable;

import dagger.Binds;
import dagger.Module;
import dagger.hilt.InstallIn;
import dagger.hilt.codegen.OriginatingElement;
import dagger.hilt.components.SingletonComponent;
import dagger.multibindings.IntoSet;
import se.ansman.deager.Initializable;

@Module
@InstallIn(SingletonComponent.class)
@OriginatingElement(
    topLevelClass = InitializableThing.class
)
public abstract class EagerInitializableThingModule {
  private EagerInitializableThingModule() {
  }

  @Binds
  @IntoSet
  public abstract Initializable bindInitializableThingAsInitializable(
      InitializableThing initializableThing);
}