// Code generated by Auto Dagger. Do not edit.
package se.ansman.provider.qualified

import dagger.Lazy
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.codegen.OriginatingElement
import dagger.hilt.components.SingletonComponent
import dagger.multibindings.IntoSet
import javax.inject.Named
import se.ansman.dagger.auto.Initializable
import se.ansman.dagger.auto.Initializable.Companion.asInitializable

@Module
@InstallIn(SingletonComponent::class)
@OriginatingElement(topLevelClass = QualifiedProviderModule::class)
public object AutoInitializeQualifiedProviderModule {
  @Provides
  @IntoSet
  public fun getThingAsInitializable(@Named(`value` = "someName")
      qualifiedProvidedThing: Lazy<QualifiedProvidedThing>): Initializable =
      qualifiedProvidedThing.asInitializable()
}