name: Build Gradle

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Cache Python
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-python-${{ env.cache-name }}-${{ hashFiles('libs.versions.toml', 'build.gradle.kts') }}
        path: .gradle/python

    - name: Run Checks
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check --continue --stacktrace --scan

  deploy-snapshot:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: checks
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Deploy Snapshot
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publishSnapshot --stacktrace
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}