name: Publish docs

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '19'

      - name: Publish Docs
        uses: gradle/gradle-build-action@v2
        env:
          GRGIT_USER: x-access-token
          GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: mkdocsPublish
