name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          repo-token: ${{ secrets.GRADLE_WRAPPER_UPDATE_TOKEN }}
